# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 13:42


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0001_initial'),
    ]

    operations = [
#        migrations.CreateModel(
#            name='User',
#            fields=[
#                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                ('password', models.CharField(max_length=128, verbose_name='password')),
#                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
#            ],
#            options={
#                'abstract': False,
#            },
#        ),
#        migrations.AlterField(
#            model_name='artist',
#            name='user',
#            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fanart.User'),
#        ),
    ]
