# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 15:43


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0005_auto_20170831_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_host',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
