# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0006_auto_20170831_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_host',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
