# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 21:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0008_auto_20170831_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
