# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 21:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0010_auto_20170831_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num_pictures',
            field=models.IntegerField(default=0),
        ),
    ]
