# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 01:42


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0011_auto_20170831_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='picture',
            name='characters',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='picture',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='date_inserted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='date_uploaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='extension',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='picture',
            name='file_size',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='picture',
            name='hash',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='picture',
            name='height',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='inserted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inserted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='picture',
            name='is_color',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='is_scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='picture',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='picture',
            name='needs_poster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='picture',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='num_faves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='quality',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='picture',
            name='rank_in_artist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='rank_in_folder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='thumb_height',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='picture',
            name='width',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='work_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='picture',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fanart.Folder'),
        ),
    ]
