# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 01:57


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0013_auto_20170901_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='latest_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_folder', to='fanart.Picture'),
        ),
        migrations.AddField(
            model_name='folder',
            name='latest_picture_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='folder',
            name='num_pictures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent_folder_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
