# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0014_auto_20170901_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_orig',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
