# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 02:57


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0017_auto_20170901_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_artist',
        ),
        migrations.AddField(
            model_name='user',
            name='artist_id_orig',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
