# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 12:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0019_auto_20170901_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='id_orig',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
