# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0020_folder_id_orig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
