# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0022_auto_20170901_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fanart.Folder'),
        ),
    ]
