# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 19:02


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0023_auto_20170901_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='inserted_by',
            new_name='approved_by',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='date_inserted',
            new_name='date_approved',
        ),
    ]
