# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-02 18:17


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0026_remove_shout_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturecomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='fanart.PictureComment'),
        ),
    ]
