# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0028_auto_20170903_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloringbase',
            name='id_orig',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='coloringpicture',
            name='id_orig',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
