# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0029_auto_20170903_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='id_orig',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
