# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 00:08


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0033_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('icon', 'Icon'), ('adoptable', 'Adoptable')], max_length=10)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('comment', models.TextField(blank=True)),
                ('filename', models.CharField(blank=True, max_length=100)),
                ('basename', models.CharField(blank=True, max_length=100)),
                ('extension', models.CharField(blank=True, max_length=5)),
                ('thumb_height', models.IntegerField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('adopted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades_offered', to=settings.AUTH_USER_MODEL)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fanart.Character')),
            ],
        ),
    ]
