# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 00:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0034_tradingoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('reference_url', models.CharField(blank=True, max_length=255)),
                ('date_fulfilled', models.DateTimeField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=100)),
                ('extension', models.CharField(blank=True, max_length=5)),
                ('date_uploaded', models.DateTimeField(blank=True, null=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fanart.TradingOffer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
