# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 00:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0035_tradingclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingclaim',
            name='id_orig',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingoffer',
            name='id_orig',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
