# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 00:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0036_auto_20170905_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingclaim',
            name='basename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
