# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0038_picturecharacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturecharacter',
            name='date_tagged',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
