# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0042_tag_id_orig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='tags',
            field=models.ManyToManyField(blank=True, to='fanart.Tag'),
        ),
    ]
