# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 13:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0043_auto_20170905_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approver',
            field=models.BooleanField(default=False),
        ),
    ]
