# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0044_user_is_approver'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_accepted', models.DateTimeField(blank=True, null=True)),
                ('hash', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fanart.Picture')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
