# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 13:57


from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0045_giftpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftpicture',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='giftpicture',
            name='hash',
            field=models.CharField(blank=True, max_length=33),
        ),
    ]
