# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0046_auto_20170905_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftpicture',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='giftpicture',
            name='hash',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
