# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0047_auto_20170905_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftpicture',
            name='hash',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
