# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 14:17


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0048_auto_20170905_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftpicture',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
