# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 15:17


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0049_giftpicture_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sketcher_mod',
            field=models.BooleanField(default=False),
        ),
    ]
