# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 19:09


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0052_socialmedia_id_orig'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnviewedPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='watchers_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unviewedpicture',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fanart.Picture'),
        ),
        migrations.AddField(
            model_name='unviewedpicture',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
