# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 02:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0059_contest_contestentry_contestvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='id_orig',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='id_orig',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
