# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 13:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0061_privatemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=32)),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
