# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 02:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0065_remove_user_is_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='User is allowed to log in.'),
        ),
    ]
