# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0067_auto_20170911_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(default=True, help_text="Controls whether user's art page is publicly visible to unauthenticated users"),
        ),
    ]
