# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 02:36


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0068_auto_20170911_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='unviewedpicture',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_pictures', to=settings.AUTH_USER_MODEL),
        ),
    ]
