# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0070_auto_20171016_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturecomment',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shout',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
