# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0071_auto_20171016_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
