# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 20:17


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0072_auto_20171023_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dir_name',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
    ]
