# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 21:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0073_auto_20171026_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='date_blocked',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
