# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 04:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0074_auto_20171026_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='latest_picture',
        ),
        migrations.AlterField(
            model_name='picture',
            name='date_approved',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='date_uploaded',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
