# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0075_auto_20171105_0410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='num_pictures',
        ),
    ]
