# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 21:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0077_character_is_canon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='date_tagged',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
