# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 04:20


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0078_character_date_tagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='num_pictures',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
