# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 01:49


from django.db import migrations, models
import fanart.models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0080_auto_20171110_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradingclaim',
            options={'ordering': ['date_posted']},
        ),
        migrations.RemoveField(
            model_name='tradingclaim',
            name='basename',
        ),
        migrations.RemoveField(
            model_name='tradingclaim',
            name='extension',
        ),
        migrations.AddField(
            model_name='tradingclaim',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingclaim',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradingclaim',
            name='filename',
            field=models.ImageField(blank=True, height_field='height', max_length=255, null=True, storage=fanart.models.OverwriteStorage(), upload_to=fanart.models.get_media_path, width_field='width'),
        ),
    ]
