# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import fanart.models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0081_auto_20171111_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingclaim',
            name='picture',
            field=models.ImageField(blank=True, height_field='height', max_length=255, null=True, storage=fanart.models.OverwriteStorage(), upload_to=fanart.models.get_claims_path, width_field='width'),
        ),
        migrations.AlterField(
            model_name='tradingclaim',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
