# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0082_auto_20171111_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coloringpicture',
            name='thumb_height',
        ),
    ]
