# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import fanart.models
import coloring_cave.models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0083_remove_coloringpicture_thumb_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloringpicture',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coloringpicture',
            name='picture',
            field=models.ImageField(blank=True, height_field='height', max_length=255, null=True, storage=fanart.models.OverwriteStorage(), upload_to=coloring_cave.models.get_coloring_path, width_field='width'),
        ),
        migrations.AlterField(
            model_name='coloringpicture',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
