# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0084_auto_20171112_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloringpicture',
            name='filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
