# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 14:56


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0087_auto_20171112_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialfeature',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fanart.Tag'),
        ),
    ]
