# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0088_specialfeature_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestentry',
            options={'ordering': ['-date_entered'], 'verbose_name_plural': 'contest entries'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag']},
        ),
        migrations.AlterField(
            model_name='contestentry',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
