# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0089_auto_20171116_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestvote',
            name='date_voted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
