# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0091_auto_20171117_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatemessage',
            options={'ordering': ['-date_sent']},
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
