# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 20:33


from django.db import migrations, models
import fanart.models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0094_auto_20171121_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, height_field='height', max_length=255, null=True, storage=fanart.models.OverwriteStorage(), upload_to=fanart.models.get_profile_path, width_field='width'),
        ),
    ]
