# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 20:48


from django.db import migrations, models
import fanart.models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0095_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, height_field='profile_height', max_length=255, null=True, storage=fanart.models.OverwriteStorage(), upload_to=fanart.models.get_profile_path, width_field='profile_width'),
        ),
    ]
