# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import fanart.models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0096_auto_20171121_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='picture',
            field=models.ImageField(blank=True, height_field='height', max_length=255, null=True, storage=fanart.models.OverwriteStorage(), upload_to=fanart.models.get_pending_path, width_field='width'),
        ),
        migrations.AlterField(
            model_name='pending',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pending',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
