# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 22:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0098_auto_20171124_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
