# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 22:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0099_auto_20171124_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturecharacter',
            name='date_tagged',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
