# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 17:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0100_auto_20171124_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending',
            name='extension',
        ),
        migrations.AlterField(
            model_name='pending',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
