# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 14:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0101_auto_20171125_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pending',
            options={'ordering': ['date_uploaded']},
        ),
        migrations.AlterField(
            model_name='giftpicture',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
