# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 02:57


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0104_auto_20171129_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('', '(No response)')], max_length=10),
        ),
    ]
