# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0105_auto_20171130_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('', 'Neither')], max_length=10),
        ),
    ]
