# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 04:27


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0106_auto_20171130_0424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='gender',
            new_name='sex',
        ),
    ]
