# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 04:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0107_auto_20171130_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
