# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 22:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0109_customicon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customicon',
            options={'ordering': ['type']},
        ),
        migrations.AddField(
            model_name='customicon',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
