# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 03:04


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fanart.models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0110_auto_20171130_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, height_field='height', max_length=255, null=True, storage=fanart.models.OverwriteStorage(), upload_to=fanart.models.get_banner_path, width_field='width')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
