# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0112_auto_20171201_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_banner_ext',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='old_banner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
