# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 02:36


from django.db import migrations, models
import fanart.models
import trading_tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0113_auto_20171201_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingoffer',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingoffer',
            name='picture',
            field=models.ImageField(blank=True, height_field='height', max_length=255, null=True, storage=fanart.models.OverwriteStorage(), upload_to=trading_tree.models.get_offers_path, width_field='width'),
        ),
        migrations.AddField(
            model_name='tradingoffer',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
