# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 02:42


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0114_auto_20171203_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingoffer',
            name='thumb_height',
        ),
    ]
