# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0115_remove_tradingoffer_thumb_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingoffer',
            name='basename',
        ),
        migrations.RemoveField(
            model_name='tradingoffer',
            name='extension',
        ),
    ]
