# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0116_auto_20171203_0254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='coloringbase',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='coloringbase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
