# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 02:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0117_auto_20171204_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloringbase',
            name='num_colored',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
