# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 13:25


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0118_auto_20171204_0247'),
        ('coloring_cave', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColoringBase',
            new_name='OldColoringBase',
        ),
        migrations.RenameModel(
            old_name='ColoringPicture',
            new_name='OldColoringPicture',
        ),
        migrations.AlterField(
            model_name='character',
            name='profile_coloring_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coloring_cave.ColoringPicture'),
        ),
    ]
