# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 20:06


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0120_auto_20171205_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingclaim',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='tradingclaim',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tradingoffer',
            name='adopted_by',
        ),
        migrations.RemoveField(
            model_name='tradingoffer',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='tradingoffer',
            name='character',
        ),
        migrations.DeleteModel(
            name='TradingClaim',
        ),
        migrations.DeleteModel(
            name='TradingOffer',
        ),
    ]
