# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 20:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0123_auto_20171208_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftpicture',
            name='date_declined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
