# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0124_giftpicture_date_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftpicture',
            name='reply_message',
            field=models.TextField(blank=True),
        ),
    ]
