# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0125_giftpicture_reply_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialFeature',
            new_name='Showcase',
        ),
    ]
