# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 22:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fanart.models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0126_auto_20171211_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_featured', models.DateField()),
                ('intro_text', models.TextField(blank=True, default='')),
                ('own_words_text', models.TextField(blank=True, default='')),
                ('analysis_text', models.TextField(blank=True, default='')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedArtistPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, height_field='height', max_length=255, null=True, storage=fanart.models.OverwriteStorage(), upload_to=fanart.models.get_featured_path, width_field='width')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('featured_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanart.FeaturedArtist')),
            ],
        ),
    ]
