# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0127_featuredartist_featuredartistpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredartist',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
