# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 18:51


from django.db import migrations, models
import fanart.models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0130_auto_20171212_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredartist',
            name='banner',
            field=models.ImageField(blank=True, height_field='banner_height', max_length=255, null=True, storage=fanart.models.OverwriteStorage(), upload_to=fanart.models.get_featured_banner_path, width_field='banner_width'),
        ),
    ]
