# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fanart.models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0131_auto_20171212_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredartistpicture',
            name='showcase_picture',
            field=models.ImageField(blank=True, height_field='height', max_length=255, null=True, storage=fanart.models.OverwriteStorage(), upload_to=fanart.models.get_featured_path, width_field='width'),
        ),
        migrations.AlterField(
            model_name='featuredartistpicture',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fanart.Picture'),
        ),
    ]
