# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 05:02


from django.db import migrations, models
import fanart.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0132_auto_20171212_2228'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pending',
            managers=[
                ('objects', fanart.models.PendingManager()),
            ],
        ),
        migrations.AlterField(
            model_name='pending',
            name='hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
