# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 14:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0134_remove_picture_thumb_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='hash',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
