# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-24 00:34


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0137_auto_20171224_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='extension',
        ),
    ]
