# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-24 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0138_remove_picture_extension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pending',
            old_name='notify_approval',
            new_name='notify_fans_of_replacement',
        ),
        migrations.RenameField(
            model_name='pending',
            old_name='notify_replacement',
            new_name='notify_on_approval',
        ),
    ]
