# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0139_auto_20171224_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
