# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-01 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0142_auto_20180225_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tooltips_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
