# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0144_modnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modnote',
            options={'ordering': ['date_created']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='folders_tree',
        ),
        migrations.RemoveField(
            model_name='user',
            name='h_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='show_community_art_box',
        ),
        migrations.RemoveField(
            model_name='user',
            name='show_contests_box',
        ),
        migrations.RemoveField(
            model_name='user',
            name='show_favorite_artists_box',
        ),
        migrations.RemoveField(
            model_name='user',
            name='show_favorite_pictures_box',
        ),
        migrations.RemoveField(
            model_name='user',
            name='show_sketcher_box',
        ),
        migrations.RemoveField(
            model_name='user',
            name='show_tool_box',
        ),
        migrations.RemoveField(
            model_name='user',
            name='v_size',
        ),
    ]
