# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0145_auto_20180305_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='zip_enabled',
        ),
    ]
