# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0146_remove_user_zip_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='old_banner_ext',
        ),
        migrations.RemoveField(
            model_name='user',
            name='old_banner_id',
        ),
    ]
