# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-10 12:22


from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0148_revisionlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revisionlog',
            old_name='comment',
            new_name='entry',
        ),
        migrations.AlterField(
            model_name='revisionlog',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
