# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-14 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0150_auto_20180310_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionlog',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
