# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-24 17:38


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0151_auto_20180314_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
