# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 01:50


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0152_auto_20180324_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allow_sketcher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sketcher_ban_reason',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sketcher_banned',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sketcher_banned_by',
        ),
    ]
