# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-20 16:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0153_auto_20180331_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='hash',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='hash',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
