# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-11 12:40


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0156_user_is_probation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_probation',
            new_name='is_under_probation',
        ),
    ]
