# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-30 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0159_bulletin_allow_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='failed_processing',
            field=models.BooleanField(default=False),
        ),
    ]
