# Generated by Django 2.1.10 on 2019-07-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0162_auto_20190709_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='height',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pending',
            name='width',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
