# Generated by Django 2.1.11 on 2019-08-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0164_featuredpicture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredpicture',
            options={'ordering': ['-date_featured']},
        ),
        migrations.AddField(
            model_name='featuredpicture',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
