# Generated by Django 2.2.10 on 2020-02-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0165_auto_20190831_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='picture',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
