# Generated by Django 2.2.10 on 2020-05-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0167_shout_reply_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shout',
            options={'ordering': ['date_posted']},
        ),
        migrations.AlterModelOptions(
            name='threadedcomment',
            options={'ordering': ['date_posted']},
        ),
    ]
