# Generated by Django 2.2.13 on 2020-07-04 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0169_auto_20200517_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
