# Generated by Django 2.2.14 on 2021-02-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0172_auto_20200823_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolboxLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order_by', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
