# Generated by Django 2.2.14 on 2021-03-15 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0173_toolboxlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
