# Generated by Django 2.2.18 on 2021-03-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0174_auto_20210315_2108'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pending',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(null=True),
        ),
    ]
