# Generated by Django 3.2.16 on 2023-01-08 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0177_auto_20230107_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='sex',
            new_name='gender',
        ),
    ]
