# Generated by Django 3.2.19 on 2023-06-18 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0178_rename_sex_character_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fanart.threadedcomment')),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fanart.shout')),
            ],
        ),
    ]
