# Generated by Django 3.2.19 on 2023-07-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0179_spamflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='spamflag',
            name='actioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
