# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-17 19:48


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_auto_20180317_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='root_pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_pms', to='pms.PrivateMessage'),
        ),
    ]
