# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 01:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sketcher', '0003_ban_ban_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='banned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sketcher_banned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
