# Generated by Django 2.2.14 on 2021-02-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketcher', '0005_auto_20190709_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawpile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked_at', models.DateTimeField()),
                ('is_running', models.BooleanField(default=False)),
                ('status_message', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
