# Generated by Django 2.2.14 on 2021-02-17 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sketcher', '0007_drawpile_admin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeuser',
            name='drawpile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sketcher.Drawpile'),
        ),
        migrations.AddField(
            model_name='ban',
            name='drawpile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sketcher.Drawpile'),
        ),
    ]
