# Generated by Django 2.2.14 on 2021-02-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketcher', '0011_auto_20210217_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawpile',
            name='drawpile_site_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
