# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 13:25
from __future__ import unicode_literals

import coloring_cave.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fanart', '0118_auto_20171204_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColoringBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orig', models.IntegerField(blank=True, db_index=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('num_colored', models.IntegerField(blank=True, default=0, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fanart.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='ColoringPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orig', models.IntegerField(blank=True, db_index=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('filename', models.CharField(blank=True, max_length=100)),
                ('picture', models.ImageField(blank=True, height_field='height', max_length=255, null=True, storage=coloring_cave.models.OverwriteStorage(), upload_to=coloring_cave.models.get_coloring_path, width_field='width')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coloring_cave.ColoringBase')),
            ],
        ),
    ]
