# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fanart.models
import trading_tree.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fanart', '0121_auto_20171205_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orig', models.IntegerField(blank=True, db_index=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('reference_url', models.CharField(blank=True, max_length=255)),
                ('date_fulfilled', models.DateTimeField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=100)),
                ('picture', models.ImageField(blank=True, height_field='height', max_length=255, null=True, storage=trading_tree.models.OverwriteStorage(), upload_to=trading_tree.models.get_claims_path, width_field='width')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('date_uploaded', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orig', models.IntegerField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('icon', 'Icon'), ('adoptable', 'Adoptable')], max_length=10)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('comment', models.TextField(blank=True)),
                ('filename', models.CharField(blank=True, max_length=100)),
                ('picture', models.ImageField(blank=True, height_field='height', max_length=255, null=True, storage=fanart.models.OverwriteStorage(), upload_to=trading_tree.models.get_offers_path, width_field='width')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('adopted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades_offered', to=settings.AUTH_USER_MODEL)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fanart.Character')),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading_tree.Offer'),
        ),
        migrations.AddField(
            model_name='claim',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
