# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-20 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def set_hash(apps, schema_editor):
    Offer = apps.get_model('trading_tree', 'Offer')
    for offer in Offer.objects.all():
        offer.hash = uuid.uuid4()
        offer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('trading_tree', '0002_auto_20180225_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='hash',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(set_hash, reverse_code=migrations.RunPython.noop)
    ]
