# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-20 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trading_tree', '0003_offer_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='hash',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
