# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-20 13:21


from django.db import migrations, models
import uuid


def set_hash(apps, schema_editor):
    Claim = apps.get_model('trading_tree', 'Claim')
    for claim in Claim.objects.all():
        claim.hash = uuid.uuid4()
        claim.save()

class Migration(migrations.Migration):

    dependencies = [
        ('trading_tree', '0003_offer_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='hash',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(set_hash, reverse_code=migrations.RunPython.noop)
    ]
